services:
  menu:
    public:    true
    class:     IndexBundle\Model\Menu
    shared: true
    arguments: ['%menu%', '@service_container', "@doctrine.orm.entity_manager"]

parameters:
    menu:
        Főmenu:
            'rank': [public]
            display: Index
        Strati:
            'rank': [owen, admin]
            display: Strati
        Blog:
          'rank': [public]
          sub:
              Blog:
                  'rank': [public]
                  display: Blog
              BlogForms:
                  'rank': [owen, admin]
                  display: BlogForms
          display: Blog
        Evmiliok:
            'rank': [public]
            sub:
                Evmiliok:
                    'rank': [public]
                    display: Evmiliok
                Keszítok:
                    'rank': [public]
                    display: Keszítok
                Tervek:
                  'rank': [public]
                  display: Tervek
                DBStatiszika:
                  'rank': [public]
                  display: DBStatiszika
            display: Evmiliok
        Oldal:
            'rank': [public]
            sub:
                Adatbazisok:
                  'rank': [public]
                  display: Adatbazisok
                HonlapStatistic:
                  'rank': [public]
                  display: HonlapStatistic
                OldalTerkep:
                  'rank': [public]
                  display: OldalTerkep
            display: Oldal
        Adminisztráció:
            'rank': [owen, admin]
            sub:
                User:
                    'rank': [public]
                    display: User
            display: Admin.