# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    parameter_name: value

#services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

parameters:
  foovalue: 'Hel贸贸贸贸ka'

services:
  foo_extension:
      public:    true
      class:     IndexBundle\Model\FooExtension
      arguments: ['%foovalue%']
      shared: true