mollewide:
  present: web/Image/Geography/present2.jpg
  pleistocene: web/Image/Geography/pleistocene2.jpg
  miocene: web/Image/Geography/miocene2.jpg
  oligocene: web/Image/Geography/oligocene2.jpg
  eocene: web/Image/Geography/eocene2.jpg
  k_t_bundary: web/Image/Geography/k_t_bundary2.jpg
  late_cretaceous: web/Image/Geography/late_cretaceous2.jpg
  early_cretaceous: web/Image/Geography/early_cretaceous2.jpg
  late_jurassic: web/Image/Geography/late_jurassic2.jpg
  middle_jurassic: web/Image/Geography/middle_jurassic2.jpg
  early_jurassic: web/Image/Geography/early_jurassic2.jpg
  late_triassic: web/Image/Geography/late_triassic2.jpg
  middle_triassic: web/Image/Geography/middle_triassic2.jpg
  late_permian: web/Image/Geography/late_permian2.jpg
  early_Peremian: web/Image/Geography/early_Peremian2.jpg
  late_penn: web/Image/Geography/late_penn2.jpg
  late_mississippian: web/Image/Geography/late_mississippian2.jpg
  middle_devonian: web/Image/Geography/middle_devonian2.jpg
  early_devonian: web/Image/Geography/early_devonian2.jpg
  early_silurian: web/Image/Geography/early_silurian2.jpg
  late_ordovician: web/Image/Geography/late_ordovician2.jpg
  middle_ordovician: web/Image/Geography/middle_ordovician2.jpg
  late_cambrian: web/Image/Geography/late_cambrian2.jpg
  early_cambrian: web/Image/Geography/early_cambrian2.jpg
  late_proterozoic: web/Image/Geography/late_proterozoic2.jpg
  latest_proterozoic: web/Image/Geography/latest_proterozoic2.jpg
globe:
  present: web/Image/Geography/present.jpg
  pleistocene: web/Image/Geography/pleistocene.jpg
  miocene: web/Image/Geography/miocene.jpg
  oligocene: web/Image/Geography/oligocene.jpg
  eocene: web/Image/Geography/eocene.jpg
  k_t_bundary: web/Image/Geography/k_t_bundary.jpg
  late_cretaceous: web/Image/Geography/late_cretaceous.jpg
  early_cretaceous: web/Image/Geography/early_cretaceous.jpg
  late_jurassic: web/Image/Geography/late_jurassic.jpg
  middle_jurassic: web/Image/Geography/middle_jurassic.jpg
  early_jurassic: web/Image/Geography/early_jurassic.jpg
  late_triassic: web/Image/Geography/late_triassic.jpg
  middle_triassic: web/Image/Geography/middle_triassic.jpg
  late_permian: web/Image/Geography/late_permian.jpg
  early_Peremian: web/Image/Geography/early_Peremian.jpg
  late_penn: web/Image/Geography/late_penn.jpg
  late_mississippian: web/Image/Geography/late_mississippian.jpg
  middle_devonian: web/Image/Geography/middle_devonian.jpg
  early_devonian: web/Image/Geography/early_devonian.jpg
  early_silurian: web/Image/Geography/early_silurian.jpg
  late_ordovician: web/Image/Geography/late_ordovician.jpg
  middle_ordovician: web/Image/Geography/middle_ordovician.jpg
  late_cambrian: web/Image/Geography/late_cambrian.jpg
  early_cambrian: web/Image/Geography/early_cambrian.jpg
  late_proterozoic: web/Image/Geography/late_proterozoic.jpg
  latest_proterozoic: web/Image/Geography/latest_proterozoic.jpg
total:
  present: web/Image/Geography/000_Ma_present-geomap_GPT-1.png
  pleistocene: web/Image/Geography/0001_Ma_PleistMaxGlac_GPT-1.png
  miocene: web/Image/Geography/010_Ma_Neo-Mio_GPT-1.png
  oligocene: web/Image/Geography/oligocene.jpg
  eocene: web/Image/Geography/040_Ma_Paleo_Eoc_GPT-1.png
  k_t_bundary: web/Image/065_Ma_K-T-GPT-1.png
  late_cretaceous: web/Image/Geography/080_Ma_Late-Cret_GPT-1.png
  early_cretaceous: web/Image/Geography/120_Ma_E-Cret_GPT-1.png
  late_jurassic: web/Image/Geography/180_Ma_Jur_GPL-1.png
  middle_jurassic: web/Image/Geography/220_Ma_Triassic_GPT-1.png
  early_jurassic: web/Image/Geography/early_jurassic.jpg
  late_triassic: web/Image/Geography/late_triassic.jpg
  middle_triassic: web/Image/Geography/middle_triassic.jpg
  late_permian: web/Image/Geography/late_permian.jpg
  early_Peremian: web/Image/Geography/early_Peremian.jpg
  late_penn: web/Image/Geography/late_penn.jpg
  late_mississippian: web/Image/Geography/340_Ma_Miss_GPT-1.png
  middle_devonian: web/Image/Geography/380_Ma_Dev_GPT-1png
  early_devonian: web/Image/Geography/early_devonian.jpg
  early_silurian: web/Image/Geography/420_Ma_Sil_GPT-1.png
  late_ordovician: web/Image/Geography/late_ordovician.jpg
  middle_ordovician: web/Image/Geography/460_Ma_Ord_GPT-1.png
  late_cambrian: web/Image/Geography/500_ma_Cambrian_GPT-1.png
  early_cambrian: web/Image/Geography/540_Ma_Cambrian_GPT-1.png
  late_proterozoic: web/Image/Geography/late_proterozoic.jpg
  latest_proterozoic: web/Image/Geography/600_Ma_Late_Proterozoic_GPT-1.png